services:
  backend:
    image: mrunknownde/biercasino-backend:latest
    container_name: biercasino_backend
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - bierbaron_net

  frontend:
    image: mrunknownde/biercasino-frontend:latest
    container_name: biercasino_frontend
    restart: unless-stopped
    ports:
      - "187:80"
    depends_on:
      - backend
    networks:
      - bierbaron_net

networks:
  bierbaron_net: