services:
 backend:
    build: ./backend
    container_name: bierbaron_backend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - bierbaron_net
 frontend:
    build: ./frontend
    container_name: bierbaron_frontend
    restart: unless-stopped
    environment:
      - VITE_API_BASE_URL=http://localhost:3000
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - bierbaron_net

networks:
  bierbaron_net:

volumes:
  db_data: